### ISSUE TITLE
getPart null value

### ISSUE THREAD

**Issue by mohadelrezk** [tipsy/spark-file-upload#1]
**I am getting an error at this line:** 

`try (InputStream input = req.raw().getPart("uploaded_file").getInputStream()) { // getPart needs to use same "name" as input field in form
`

**error:**

> java.lang.IllegalStateException: No multipart config for servlet
> 	at org.eclipse.jetty.server.Request.getPart(Request.java:2039)
> 	at javax.servlet.http.HttpServletRequestWrapper.getPart(HttpServletRequestWrapper.java:386)
> 	at eu.opengov.cubebuilder.webservice.OgiWebService.lambda$7(OgiWebService.java:203)
> 	at eu.opengov.cubebuilder.webservice.OgiWebService$$Lambda$9/672320506.handle(Unknown Source)
> 	at spark.RouteImpl$1.handle(RouteImpl.java:61)
> 	at spark.http.matching.Routes.execute(Routes.java:61)
> 	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
> 	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:451)
> 	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
> 	at java.lang.Thread.run(Thread.java:745)

I am just deploying your code as it is.
any ideas?

**Comment by tipsy** [comment]
You haven't changed anything, you just cloned and ran the example?

**Comment by mohadelrezk** [comment]
yes

**Comment by tipsy** [comment]
That's very odd. What browser/os is this?
